/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.pastor.presentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        mbaMenu = new javax.swing.JMenuBar();
        jmeClientes = new javax.swing.JMenu();
        jmiMostrarClientes = new javax.swing.JMenuItem();
        jmiAgregarCliente = new javax.swing.JMenuItem();
        jmeCuentas = new javax.swing.JMenu();
        jmiMostrarCuentas = new javax.swing.JMenuItem();
        jmiAgregarCuenta = new javax.swing.JMenuItem();
        jmeMovimientos = new javax.swing.JMenu();
        jmiMostrarMovimientos = new javax.swing.JMenuItem();
        jmiAñadirMovimiento = new javax.swing.JMenuItem();
        jmeOpciones = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmeClientes.setText("Clientes");

        jmiMostrarClientes.setText("Mostrar Clientes");
        jmiMostrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMostrarClientesActionPerformed(evt);
            }
        });
        jmeClientes.add(jmiMostrarClientes);

        jmiAgregarCliente.setText("Agregar Cliente");
        jmiAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarClienteActionPerformed(evt);
            }
        });
        jmeClientes.add(jmiAgregarCliente);

        mbaMenu.add(jmeClientes);

        jmeCuentas.setText("Cuentas");

        jmiMostrarCuentas.setText("Mostrar Clientes");
        jmiMostrarCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMostrarCuentasActionPerformed(evt);
            }
        });
        jmeCuentas.add(jmiMostrarCuentas);

        jmiAgregarCuenta.setText("Agregar Cliente");
        jmiAgregarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarCuentaActionPerformed(evt);
            }
        });
        jmeCuentas.add(jmiAgregarCuenta);

        mbaMenu.add(jmeCuentas);

        jmeMovimientos.setText("Movimientos");

        jmiMostrarMovimientos.setText("Mostrar Movimientos");
        jmiMostrarMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMostrarMovimientosActionPerformed(evt);
            }
        });
        jmeMovimientos.add(jmiMostrarMovimientos);

        jmiAñadirMovimiento.setText("Agregar Movimiento");
        jmiAñadirMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAñadirMovimientoActionPerformed(evt);
            }
        });
        jmeMovimientos.add(jmiAñadirMovimiento);

        mbaMenu.add(jmeMovimientos);

        jmeOpciones.setText("Opciones");

        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jmeOpciones.add(jmiSalir);

        mbaMenu.add(jmeOpciones);

        setJMenuBar(mbaMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiMostrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMostrarClientesActionPerformed
        new ClienteListado().setVisible(true);
    }//GEN-LAST:event_jmiMostrarClientesActionPerformed

    private void jmiAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarClienteActionPerformed
        new ClienteForm().setVisible(true);
    }//GEN-LAST:event_jmiAgregarClienteActionPerformed

    private void jmiAgregarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarCuentaActionPerformed
        new CuentaForm().setVisible(true);
    }//GEN-LAST:event_jmiAgregarCuentaActionPerformed

    private void jmiMostrarCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMostrarCuentasActionPerformed
        new CuentaListado().setVisible(true);
    }//GEN-LAST:event_jmiMostrarCuentasActionPerformed

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiMostrarMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMostrarMovimientosActionPerformed
        JOptionPane.showMessageDialog(this, "Para mostrar los movimientos de un cliente, vaya a cliente y seleccione uno", "Mostrar Movimientos", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jmiMostrarMovimientosActionPerformed

    private void jmiAñadirMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAñadirMovimientoActionPerformed
        new MovimientoForm().setVisible(true);
    }//GEN-LAST:event_jmiAñadirMovimientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jmeClientes;
    private javax.swing.JMenu jmeCuentas;
    private javax.swing.JMenu jmeMovimientos;
    private javax.swing.JMenu jmeOpciones;
    private javax.swing.JMenuItem jmiAgregarCliente;
    private javax.swing.JMenuItem jmiAgregarCuenta;
    private javax.swing.JMenuItem jmiAñadirMovimiento;
    private javax.swing.JMenuItem jmiMostrarClientes;
    private javax.swing.JMenuItem jmiMostrarCuentas;
    private javax.swing.JMenuItem jmiMostrarMovimientos;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JMenuBar mbaMenu;
    // End of variables declaration//GEN-END:variables
}
